name = "ecommerce-frontend"
compatibility_date = "2024-03-08"

# This is the critical missing part
[build]
command = "npm run build"
[build.upload]
format = "directory"
pages_build_output_dir = ".vercel/output/static"