name = "ecommerce-frontend"
compatibility_date = "2024-03-08"

[build]
command = "./emergency-fix.sh"

[site]
bucket = ".vercel/output/static"

[build.upload]
format = "directory"
pages_build_output_dir = ".vercel/output/static"