# wrangler.toml
name = "ecommerce-frontend"
main = ".next/server/index.js"
compatibility_date = "2025-03-06"

[site]
bucket = ".next"

[build]
command = "npm run build:cloudflare"

[env.production]
workers_dev = true